version: 2.1
jobs:
  compile:
   docker:
      - image: ghcr.io/neutron-toolchains/docker-image:arch-neutron
   steps:
      - run:
          no_output_timeout: 50m
          command: |
           git clone https://github.com/fskhri/kernel-xiaomi-surya -b sbv6 kernel 
           cd kernel
           git submodule update --init --remote KernelSU
           wget https://raw.githubusercontent.com/fskhri/kernel-xiaomi-surya/sbv6/.circleci/build.sh
           chmod +x myscripts/clang-setup.sh
           chmod +x myscripts/surya.sh
           source ./myscripts/clang-setup.sh
           ./myscripts/surya.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
