version: 2.1
jobs:
  compile:
    docker:
      - image: ubuntu:22.04
    steps:
      - run:
          command: |
            apt-get -y update && apt-get -y install sudo
            sudo apt-get -y upgrade
            sudo apt-get -y install bc build-essential zip curl libstdc++6 git wget python3 gcc clang libssl-dev repo rsync flex bison
            git config --global user.name "fskhri"
            git config --global user.email "fakhrijuanda88@gmail.com"
            git config --global color.ui false
            git clone https://github.com/akhilnarang/scripts && cd scripts && bash setup/android_build_env.sh && cd ..
            mkdir kernul
            cd kernul
            wget https://raw.githubusercontent.com/fskhri/kernel-xiaomi-surya/sbv6/.circleci/build.sh
            source build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile